=== Meearlyam/BSU/WEB/web_lab7/schema.xsd
<?xml version="1.0"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.bsu.by"
        xmlns="http://www.bsu.by"
        elementFormDefault="qualified">

    <xs:complexType name="Staff" abstract="true">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="salary" type="xs:double"/>
            <xs:element name="experience" type="xs:double"/>
            <xs:element name="department" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="FinancialJob" abstract="true">
        <xs:complexContent>
            <xs:extension base="Staff">
                <xs:sequence>
                    <xs:element name="reports" type="xs:int"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Accountant">
        <xs:complexContent>
            <xs:extension base="FinancialJob">
                <xs:sequence>
                    <xs:element name="areas" type="xs:int"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Receptionist">
        <xs:complexContent>
            <xs:extension base="FinancialJob">
                <xs:sequence>
                    <xs:element name="calls" type="xs:int"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Workman" abstract="true">
        <xs:complexContent>
            <xs:extension base="Staff">
                <xs:sequence>
                    <xs:element name="shifts" type="xs:int"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Foreman">
        <xs:complexContent>
            <xs:extension base="Workman">
                <xs:sequence>
                    <xs:element name="subordinated" type="xs:int"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Loader">
        <xs:complexContent>
            <xs:extension base="Workman">
                <xs:sequence>
                    <xs:element name="maxKilos" type="xs:int"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Welder">
        <xs:complexContent>
            <xs:extension base="Workman">
                <xs:sequence>
                    <xs:element name="isShipbuilder" type="xs:boolean"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="StaffList">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="foreman" type="Foreman"/>
                    <xs:element name="loader" type="Loader"/>
                    <xs:element name="welder" type="Welder"/>
                    <xs:element name="accountant" type="Accountant"/>
                    <xs:element name="receptionist" type="Receptionist"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== Meearlyam/BSU/WEB/web_lab7/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<StaffList
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.bsu.by"
        xsi:schemaLocation="http://www.bsu.by schema.xsd">

    <accountant>
        <name>Accountant1</name>
        <salary>190.50</salary>
        <experience>3.4</experience>
        <department>Financial department</department>
        <reports>20</reports>
        <areas>4</areas>
    </accountant>

    <foreman>
        <name>Foreman1</name>
        <salary>220.50</salary>
        <experience>5.2</experience>
        <department>Workman department</department>
        <shifts>15</shifts>
        <subordinated>20</subordinated>
    </foreman>

    <welder>
        <name>Welder1</name>
        <salary>260.45</salary>
        <experience>8.4</experience>
        <department>Workman department</department>
        <shifts>12</shifts>
        <isShipbuilder>false</isShipbuilder>
    </welder>

    <receptionist>
        <name>Receptionist1</name>
        <salary>140.20</salary>
        <experience>5.1</experience>
        <department>Financial department</department>
        <reports>15</reports>
        <calls>40</calls>
    </receptionist>

    <foreman>
        <name>Foreman2</name>
        <salary>420.50</salary>
        <experience>14.8</experience>
        <department>Workman department</department>
        <shifts>10</shifts>
        <subordinated>70</subordinated>
    </foreman>

    <welder>
        <name>Welder2</name>
        <salary>280.20</salary>
        <experience>4.1</experience>
        <department>Workman department</department>
        <shifts>18</shifts>
        <isShipbuilder>true</isShipbuilder>
    </welder>

    <receptionist>
        <name>Receptionist2</name>
        <salary>190.45</salary>
        <experience>6.3</experience>
        <department>Financial department</department>
        <reports>13</reports>
        <calls>53</calls>
    </receptionist>

    <loader>
        <name>Loader1</name>
        <salary>180.0</salary>
        <experience>1.1</experience>
        <department>Workman department</department>
        <shifts>25</shifts>
        <maxKilos>120</maxKilos>
    </loader>

    <loader>
        <name>Loader2</name>
        <salary>130.0</salary>
        <experience>0.6</experience>
        <department>Workman department</department>
        <shifts>20</shifts>
        <maxKilos>80</maxKilos>
    </loader>

    <accountant>
        <name>Accountant2</name>
        <salary>124.25</salary>
        <experience>1.2</experience>
        <department>Financial department</department>
        <reports>10</reports>
        <areas>2</areas>
    </accountant>


</StaffList>
